[package]
name = "target-gen"
version = "0.1.0"
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { git = "https://github.com/probe-rs/probe-rs.git" }
cmsis-pack = { git = "https://github.com/probe-rs/cmsis-pack-manager.git" }
goblin = "*"
scroll = "*"
num-traits = "*"
num-derive = "*"
serde = "1.0.101"
serde_yaml = "*"
log = "0.4.8"
zip = "0.5.3"
