[package]
name = "target-gen"
version = "0.1.0"
authors = ["Noah Huesser <yatekii@yatekii.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
probe-rs = { git = "https://github.com/probe-rs/probe-rs.git", default-features = false }
cmsis-pack = { git = "https://github.com/probe-rs/cmsis-pack-manager.git" }
goblin = "0.1.3"
scroll = "0.10.1"
num-traits = "0.2.10"
num-derive = "0.3.0"
serde = "1.0.101"
serde_yaml = "0.8.11"
log = "0.4.8"
zip = "0.5.3"
structopt = "0.3.2"
base64 = "0.11.0"
pretty_env_logger = "0.3"
